# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token b3e6e3c5ab3476586600d44328fbf7f5ebadd008

{
  "title": "Шкаф IKE",
  "description": "Срочн"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/7/
Content-Type: application/json
Authorization: Token b3e6e3c5ab3476586600d44328fbf7f5ebadd008

{
  "status": "CLOSED"
}

###


# попытка удалить объявление
DELETE {{baseUrl}}/advertisements/6/
Content-Type: application/json
# Authorization: Token b3e6e3c5ab3476586600d44328fbf7f5ebadd008



###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
