# примеры API-запросов

@baseUrl = http://127.0.0.1:8000/api/v1/
@token = 6eb321d8d11ba5ebbd3ffd3da5ffd374b2bb7421
# @token = f91c330ffb7d13e73433835fc9444f9815fb308f



# получение объявлений
GET {{baseUrl}}articles/
Content-Type: application/json
# Authorization: Token {{token}}

###

POST {{baseUrl}}articles/
Content-Type: application/json
Authorization: Token {{token}}

{
  "title": "demo",
  "tags": [1]


}

###


PATCH {{baseUrl}}articles/1/
Content-Type: application/json
Authorization: Token {{token}}

{
  "title": "demo3",
  "tags": [1]


}

###
