# Generated by Django 4.2.14 on 2024-07-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_alter_measurement_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='image',
            field=models.ImageField(default=None, upload_to='image/'),
        ),
    ]
