# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/all/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/new/
Content-Type: application/json

{
  "name": "ESP37",
  "description": "Датчик спальня"
}
###
# удалить датчик
DELETE  {{baseUrl}}/sensors/del/
Content-Type: application/json

{
  "id": 9,
  "name": "ESP34",
  "description": "Датчик спальня"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/1/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 3,
  "temperature": 25.32
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/3/
Content-Type: application/json

###

# получение информации по датчику
GET {{baseUrl}}/measurement/all/
Content-Type: application/json
